version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    networks:
      - publicare

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - publicare

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: publicare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - publicare

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - publicare

volumes:
  postgres_data:

networks:
  publicare:
    driver: bridge
